# system:
#   base_path: "./rag_data"
#   collection_name: "documents"

document_loader:
  file_path: "data/raw/"
  text_content: false
  

processing:
  chunk_size: 1000  
  chunk_overlap: 200 
  add_start_index: true 

vector_store_manager:
  collection_name: "example_collection_1536"
  persist_directory: "./data/processed"
  vector_size: 1536

retrieval:
  num_chunks: 5
  min_relevance_score: 0.7